### ISSUE TITLE
Editing a game's tooltypes from within iGame destroys it's newicon.

### ISSUE THREAD

**Issue by MrZammler** [MrZammler/iGame#1]
Make sure the IM= structure from the info file is kept and re-written when the tooltypes are edited.

**Comment by midwan** [comment]
@MrZammler 
Is this still going on? I haven't noticed a problem here, but perhaps the icons I'm using are of a newer standard (Glowicons?). And I'm also not sure if the `icon.library` in the system is relevant to this, as I'm using the latest IconLib from Aminet.

**Comment by walkero-gr** [comment]
This should be fixed in [2.3.0](https://github.com/MrZammler/iGame/releases/tag/v2.3.0) release. If not, please reopen this ticket
