### ISSUE TITLE
Option for Screenshot size

### ISSUE THREAD

**Issue by midwan** [MrZammler/iGame#10]
It would be nice to have an option for the screenshot size.
Maybe it would make sense to have that window scalable?

**Comment by MrZammler** [comment]
Hi.

Well, there is something like that. There is a tooltype called SCREENSHOT and can be set to a specific dimension for the screenshot box. (eg SCREENSHOT=128x100).

Plus, iGame tries to have a proper screenshot box when it starts depending on the resolution it's running if the tooltype is not present.

But, yeah, maybe being able to resize while running would be nice.

**Comment by midwan** [comment]
Added the known supported Tooltypes to the Wiki:
https://github.com/MrZammler/iGame/wiki/Tooltypes

Please update it there if I missed anything.

Closing this for now, as there's already an option. We can add a Settings window separately and include this there, in the future.
