### ISSUE TITLE
No Games in the gamelist once iGame 2020-09-06 is closed.

### ISSUE THREAD

**Issue by M1kerochip** [MrZammler/iGame#100]
I've never used iGame before, so, this is a clean install.

Stock A1200, 8mb fast ram, AmigaOS 3.1.4, Kickstart 3.1.4, MUI 3.8, copied in the guigfx_render_nofpu.lha files.

Load iGame, select the WHDLoad games folder I have, set "set title from folder", scan for games.
After some minutes, the games list appears, and I can see all games.

Launching games etc, works perfectly.

Close iGame, the gamelist .csv gets created, but, on loading, the games list is blank.

**Comment by walkero-gr** [comment]
@M1kerochip Thank you for this report. Can you please tell me the size of the CSV file? Can you attach it here?

**Comment by M1kerochip** [comment]
Sure!
[Commodore_Amiga_WHDLoad.zip](https://github.com/MrZammler/iGame/files/5203295/Commodore_Amiga_WHDLoad.zip)

**Comment by walkero-gr** [comment]
@M1kerochip There is no problem with the CSV file. iGame is configured to start by showing the Favorite games, and there is none selected in this list as favorite. That's why when you start it again, nothing is on the list selected. Try to open iGame and select from the categories list at the right the "Show All", and the list will show up.

**Comment by M1kerochip** [comment]
You are indeed correct!
I had set favourites earlier, but, I remember deleting the .csv for some reason. I obviously never set them back up again!!
OK, thanks for that!
The only thing then, I can suggest, is, when there's afilter selected, instead of saying "Total games X" on the status bar, it says something like "Visible games Y of X" where X is the total, and Y is the filtered amount.

If I'd seen "Visible 0 games of 3,000" I'd hope I wouldn't have made this mistake! 👍
Or maybe "0 visible favourites of 3,000 total"
Anyhow, thanks again!

**Comment by walkero-gr** [comment]
@M1kerochip Thank for the recommendation. We will for make something that will be more helpful.

**Comment by M1kerochip** [comment]
Great, thanks!

Another suggestion is that the word 'Favourites' be highlighted in the filter list, if you're starting with show favourites on startup, but if not, have 'Show all games' highlighted?
