### ISSUE TITLE
"Show/hide hidden entries" does it work?

### ISSUE THREAD

**Issue by walkero-gr** [MrZammler/iGame#107]
@MrZammler  @coldacid Yesterday I tried the "Show/hide hidden entries" and on my system it was disabling the filter field and the genre list, while it cleared my games list. That's what it should do? I am asking because I am not that familiar with this choice and maybe it doesn't work as it should

Tested v2.0b6

**Comment by coldacid** [comment]
I've never used it myself.

**Comment by walkero-gr** [comment]
This menu item shows or hides the hidden entries. It disables the filter and the genres list because it clears the games list and show only the hidden entries. So, it seems it works the way it was designed to work.
