### ISSUE TITLE
Is "MUI Builder" file still needed?

### ISSUE THREAD

**Issue by walkero-gr** [MrZammler/iGame#110]
@MrZammler Do we need to keep the MUI Builder file? Since most of the changes we do on the GUI are done straight to the code, I doubt the MUI Builder file is still needed. Should we remove it or keep it in an "obsolete" folder?

**Comment by coldacid** [comment]
Given how Git works, if it's not needed we can and should just delete the directory. If anything's needed from it, individual files can be checked out from past commits.

**Comment by MrZammler** [comment]
Hi, we should keep it I think, even if it doesn't anymore represent the current state of the GUI, at least as a base. If we need to add more GUI stuff, it could be difficult to do it in code, and might require MUI Builder again.

**Comment by coldacid** [comment]
@MrZammler just because it's deleted doesn't mean it would be gone. The files could still be restored from existing commits in the repository. The files would only be removed from the commit doing the deletion and those parented on it.

**Comment by walkero-gr** [comment]
This is moved into obsolete folder for now.
