### ISSUE TITLE
Italian catalog updated

### ISSUE THREAD

**Issue by samo79** [MrZammler/iGame#116]
Attached the updated version of the italian catalog, fell free to include it in repository and final archive release :-)

Link:

https://files.fm/u/fq9d79zw

**Comment by walkero-gr** [comment]
@samo79 Thank you so much. I will add it to the package and also update the installer to include at the language selection.

**Comment by samo79** [comment]
Thanks mate, meanwhile me and Thore we are still investigate about a possible problem related to the newest guigfx.mcc MUI class

https://muidev.de/ticket/453

iGame seems a good test example for debugging this class aswell..

**Comment by walkero-gr** [comment]
@samo79 If I am not wrong, in the guigfx archive there is a demo, that uses the render library as well. Try this also if it crashes, so to be sure there is not a problem of iGame.

**Comment by samo79** [comment]
Apparently it was a bug related to the newer version of the guigfx.mcc class in development.
I'm waiting for the next nightly build of MUI in order to verify if this issue was finally solved or not.
Important to say: In the future release of MUI (5.0) this class, along with the render.library will be finally integrated in both 68k an PowerPC MUI5 packages, this means there will be no need to install the old class from Aminet anymore!
