### ISSUE TITLE
Installer break under OS4

### ISSUE THREAD

**Issue by samo79** [MrZammler/iGame#129]
As release 2.0 seems close to completation i had a quick try with latest release to check if everything worked

Noted a couple of issues:

1) Installation procedure breaks with this error:

MAKEDIR: No prompt specified at line 260

2) As i can't install it yet, i wanted atleast to verify if italian catalog worked; but seems not.
I try to put it in "sys:locale/catalogs/italian" and even mantain it into the program folder defauk directory.. but both solution does not work.. program will only loaded in english.

Maybe before releasing 2.0 officially you probably need to fix these 2 issues

**Comment by walkero-gr** [comment]
@samo79 
You used the version that released today?
About the installer, I am pretty sure it works fine under OS4. I just did install it and had no issues. Please give me some more info on what you did.

About the catalog, I thought this was working when you sent me the new catalogs. But anyway, there is a known issue at #103 which we will work for the next beta version of v2.1. So, most possible we will have it sorted really soon.

**Comment by samo79** [comment]
Yes i'm using the latest version released today :-)

About the installer issue: The installer breaks with that error when it reach the "language installation" section, as soon as i select the checkbox english or italian (or both of them) it give me the error...

About localization: No i never tried it for real, even because at the end that translation wasn't so big to "force" me to test if everthing was corrected or not... however when i was about to test the whole package i discover that locale in reality still was not fully implemented!

I can of course wait for next release, but to be honest it would be cool if this could be fixed now

**Comment by walkero-gr** [comment]
@samo79 Do you try to install above and old installation or at a partition where there is no iGame folder?

**Comment by samo79** [comment]
No, there wasn't present any old version of iGame, more I was installing it in a fresh new partition :-)

**Comment by walkero-gr** [comment]
@samo79 Found the problem and I already fixed it. It will be on the next beta version.
Thanks for reporting this issue.
