### ISSUE TITLE
Show release version in wb titlebar

### ISSUE THREAD

**Issue by samo79** [MrZammler/iGame#130]
Current program release version could be showed also in Workbench's titlebar, so users will have an immediate visualization of the specific release version they are currently installed on.

To implement this you will need to use the "MUIA_Window_ScreenTitle" .. This will show the text in the screens title bar when the window of the program is active.  

https://muidev.de/wiki/Documentation/API/MUI_Window#MUIA_Window_ScreenTitle

**Comment by walkero-gr** [comment]
@samo79 Maybe we can add it in feature version. Thanks for your comment.

**Comment by samo79** [comment]
Yep hopefully for 2.1 .. still waiting for this, so beside other things i can test my translation aswell

**Comment by walkero-gr** [comment]
@samo79 Please check the iGame v2.1b1 for the Italian catalog if it works or not. If you need to do any changes, please send me the new version.

**Comment by samo79** [comment]
Yeah it works, but i had to applicate some more fix :-)
Here is the new version:

http://s000.tinyupload.com/index.php?file_id=91604723032585072506
