### ISSUE TITLE
Small right column

### ISSUE THREAD

**Issue by walkero-gr** [MrZammler/iGame#133]
A user mentioned that the right column is much smaller than the screenshot and it looks as the screen below.
Some info of his setup:

> MUI Version 3.8 (unregistered)
> The screenshots are 320x128
> I turn off GUIGfx because when it's enabled iGame doesn't load for me..

This is not a show stopper but would be good to fix.

![igame](https://user-images.githubusercontent.com/14014909/97911746-b284e400-1d43-11eb-9712-1e32fd367e11.png)

**Comment by coldacid** [comment]
This is *because* GuiGfx is turned off. GuiGfx is what's being used to scale the screenshot. When it is disabled, the screenshot control takes the native size of the screenshot image that has been loaded.

**Comment by walkero-gr** [comment]
This should be fixed in [2.3.2](https://github.com/MrZammler/iGame/releases/tag/v2.3.2) release. If not, please reopen this ticket
