### ISSUE TITLE
ClassicWB Lite: Getting Program failed on iGame start

### ISSUE THREAD

**Issue by olliraa** [MrZammler/iGame#136]
Hi all.

I have the required libs in their places (or so I think, at least). However, I only get this error (see pic below):

![image](https://user-images.githubusercontent.com/16563995/106561097-c43b7a80-6530-11eb-817a-40b990ccb1cd.png)

Could someone have a clue, what's causing this? All other software works without any problems. 

*EDIT*
Snoopdos log below:

SnoopDos logging started on Tuesday, 02-Feb-21 at 11:55:59

 Count Process Name       Action     Target Name                 Options Res.
 ----- ------------       ------     -----------                 ------- ----
 1     ramlib             Load       LIBS:asl.library                    OK  
 2     iGame              ChangeDir  Boot:Programs/igame20/iGame             
 3     iGame              Open       NIL:                        Read    OK  
 4     ramlib             Load       LIBS:muimaster.library              OK  
 5     ramlib             Load       LIBS:muigfx.library                 OK  
 6     ramlib             Load       LIBS:muilowlevel.library            OK  
 7     iGame              Open       keypath:mui.key             Read    Fail
 8     iGame              Open       keyfiles:mui.key            Read    Fail
 9     iGame              Open       S:mui.key                   Read    OK  
 10    ramlib             Load       LIBS:muiconfig.library              OK  
 11    iGame              Open       env:mui/«Global».prefs      Read    OK  
 12    ramlib             Load       LIBS:mui/TextEditor.mcc             OK  
 13    ramlib             Load       LIBS:cybergraphics.library          Fail
 14    ramlib             Load       cybergraphics.library               Fail
 15    ramlib             Load       LIBS:lowlevel.library               OK  
 16    iGame              Open       PROGDIR:igame.prefs         Read    Fail
 17    iGame              ToolType   SCREENSHOT                          Fail
 18    iGame              ToolType   NOGUIGFX                            Fail
 19    iGame              ToolType   FILTERUSEENTER                      Fail
 20    iGame              ToolType   NOSCREENSHOT                        Fail
 21    iGame              ToolType   SAVESTATSONEXIT                     Fail
 22    iGame              ToolType   TITLESFROMDIRS                      Fail
 23    iGame              ToolType   NOSMARTSPACES                       Fail
 24    iGame              ToolType   NOSIDEPANEL                         Fail
 25    iGame              LockScreen Workbench                           OK  
 26    ramlib             Load       LIBS:render.library                 OK  
 27    ramlib             Load       LIBS:guigfx.library                 OK  
 28    ramlib             Load       LIBS:datatypes.library              OK  
 29    ramlib             Load       LIBS:cybergraphics.library          Fail
 30    ramlib             Load       cybergraphics.library               Fail
 31    ramlib             Load       LIBS:mathtrans.library              OK  
 32    ramlib             Load       LIBS:mui/Guigfx.mcc                 OK  
 33    ramlib             Load       LIBS:cybergraphics.library          Fail
 34    ramlib             Load       cybergraphics.library               Fail
 35    ramlib             Load       LIBS:cybergraphics.library          Fail
 36    ramlib             Load       cybergraphics.library               Fail
 37    iGame              Open       Boot:Programs/igame20/iGame Read    OK  
 38    ramlib             Load       LIBS:datatypes/ilbm.datatyp         OK  
 39    ramlib             Load       LIBS:datatypes/picture.data         OK  
 40    iGame              Open       PROGDIR:igame.iff           Read    OK  
 41    ramlib             Load       LIBS:mui/Popasl.mui                 OK  
 42    ramlib             Load       LIBS:muirexx.library                OK  
 43    iGame              Open       PROGDIR:gameslist           Read    Fail
 44    iGame              Open       PROGDIR:repos.prefs         Read    Fail
 45    iGame              Open       PROGDIR:genres              Read    Fail
 46    iGame              ChangeDir  Boot:Programs/igame20/iGame             
 47    ramlib             Load       LIBS:muiconfig.library              OK  
 48    iGame              Open       env:mui/IGAME.1.cfg         Read    Fail
 49    iGame              Open       env:mui/IGAME.1.cfg         Read    Fail
 50    ramlib             Load       LIBS:cybergraphics.library          Fail
 51    ramlib             Load       cybergraphics.library               Fail`

Specs:

A600, Furia 40Mhz (recapped etc.)
2MB Chip, 8MB Fast
32GB sd-card HD
ClassicWB Lite v28
Latest iGame

**Comment by walkero-gr** [comment]
Most possible some library is missing or is not compatible with your machine. 
Which version of iGame do you run? I suspect that you have an old version.

If you have iGame v2 try to run it from shell. You will get more info of what is missing.
You can also try to disable GUIGFX or even SCREENSHOTS by disabling those tooltypes on iGame icon.

Please come back and tell us how it went.

**Comment by olliraa** [comment]
Hi. Thanks for the reply. I have the iGame2.0, latest realeased version, namely 16102020. Rnuning from shell -> no shell output and same result. Disabling those tooltypes --> same result.

I forgot to tell you that in addition to that error I I get an empty window drawn on the screen.

The Snoopdos log does not tell anything? I was hoping it could help.

**Comment by walkero-gr** [comment]
Do you have a config file in the same folder, named igame.prefs? If yes, delete it or rename it and try to run it again.
Can you attach here a screenshot of the icon tooltypes?
Which version of MUI are you using?

Thank you so much for your help to track the problem.

**Comment by olliraa** [comment]
I have no prefs fil, it does not get created. Yo can see the contents of the freshly installed Igame 2.0 below:
![image](https://user-images.githubusercontent.com/16563995/106645762-786eec80-6595-11eb-9f43-d2b92680dab0.png)

Tooltypes are as follows:
![image](https://user-images.githubusercontent.com/16563995/106645804-845aae80-6595-11eb-9d5f-db955fd58c1a.png)

**Comment by walkero-gr** [comment]
I downloaded ClassicWB Lite to try it myself here and find if there is an incompatibility.
Please add the following to the tooltypes and check if it works
NOGUIGFX
NOSCREENSHOT

**Comment by olliraa** [comment]
With those Tooltypes it actually starts! :) Thank you! There's still no prefs-file, though.

**Comment by walkero-gr** [comment]
The prefs file will be created as soon as you open the Settings windows and click the save button.
It seems you have issues with GuiGfx. Try to put NOSCREENSHOT in parenthesis. It might work and start with a screenshot, but this way it doesn't use the GuiGfx, which means that the screenshots will have a standard size.
If you want to make GuiGfx to work, read the guide file that comes with iGame, and if you need more help, do not hesitate to write here.

**Comment by olliraa** [comment]
If I set (NOSCREENSHOT) it crashes again. Any clues? All the libs and MUI have been installed according to the instructions.

**Comment by walkero-gr** [comment]
Possible there is an issue with your datatypes which iGame uses to show the images. Try to open iGame.iff, which is included in the iGame archive with Multiview and please inform me if it works. If not, there is an issue that can be fixed from the installed datatypes of your system.

Which is interesting as an issue, because I downloaded and installed ClassicWB Lite on my machine, and it works fine, with screenshots showing up as they should. Do you use a special version of the system? Any specific datatypes?

**Comment by olliraa** [comment]
Ok, the iGame.iff opens up just fine. Weird. I run the standard version of ClassicWB Lite. Do you run the Full version?

**Comment by olliraa** [comment]
Got it working. Replaced my startupsequence with the original one from CWB Lite. There must have been something broken in the ss earlier. Sorry about the hassle, but I'm glad it works now :)

**Comment by walkero-gr** [comment]
I am glad it works fine for you. Out of curiosity, I would like to know what is the difference between your S-S and the CWB one. Maybe we can add a check and a notice on iGame to avoid crashes in future release. 
Thank you for your messages.

**Comment by olliraa** [comment]
I had somehow managed to change the "minimum" version of the ss into the "full" one --> A600 booted with the minimum ss instead of the full one. Here are the files:

[Startup-Sequence_full.txt](https://github.com/MrZammler/iGame/files/5923351/Startup-Sequence_full.txt)
[Startup-Sequence_min.txt](https://github.com/MrZammler/iGame/files/5923352/Startup-Sequence_min.txt)

**Comment by walkero-gr** [comment]
Thanks a lot for attaching them. I will have a look.
