### ISSUE TITLE
Create a better way to parse the game/demo icon tooltypes

### ISSUE THREAD

**Issue by walkero-gr** [MrZammler/iGame#141]
We need to change the way iGame parses the games'/demos' tooltypes, so that we prevent the possibility to use wrong arguments when executing whdload.

We can also make wbrun default, where possible, instead of the shell execution of whdload.

**Comment by wepl** [comment]
You could use the template returned from 'whdload ?' to check for valid options.
Otherwise using wbrun would have the benefit that whdload would be able to write back selected options from the splash window back to the icon.

**Comment by walkero-gr** [comment]
After some investigation I found that WHDLoad games cannot run with WBRun, because there is no binary, except of an icon file, that uses whdload as default tool and the slave file in tooltypes.

**Comment by MrV2K** [comment]
I use KGIconload by killergorilla to launch games from my windows based frontend. It parses the tooltypes and isn't reliant on a binary file. [(http://eab.abime.net/showpost.php?p=584390&postcount=72)]

**Comment by DisasterIncarnate** [comment]
> After some investigation I found that WHDLoad games cannot run with WBRun, because there is no binary, except of an icon file, that uses whdload as default tool and the slave file in tooltypes.

i have a work in progress launcher of my own which is more of an early boot/startup-sequence selector but can run whdloaded stuff and i just "WBRUN GameName" and that launches it just fine even without a binary present.
I also use https://aminet.net/package/util/cli/IInfo to pop up the icon for GameName, where i trim off the .info from the filename and IInfo pops up the icon for editing.

It is best when the icon/info file has the same name as the slave file:

ExampleGame.info
ExampleGame.slave

if ExampleGame.info has the tooltype SLAVE=SomeotherExample.slave, then it kinda doesnt work, but most entries i find like that, which is rare, I correct manually at the moment, there is probably a more clever way to do it by renaming the .slave present to the same name as the games .info ofc.

But yeah, you can WBRUN the games icon, you just dont include the .info

**WBRUN GameName.info** doesnt work but.
**WBRUN GameName** does launch the game without an actual gameName executable of any kind.

**Comment by walkero-gr** [comment]
This will not be fixed because on some OSes users use extra execute tooltypes that are not part of WHDLoad, but necessary for a good gaming experience
