### ISSUE TITLE
iGame not starting

### ISSUE THREAD

**Issue by gustavosarmento** [MrZammler/iGame#143]
A600 / KS-WB 3.1 / 2 MB chip / 4 MB fast

Just installed MUI, iGame and the required libraries, but when I double click it, nothing happens. 

Any ideas of what the issue is?

Thanks!

**Comment by walkero-gr** [comment]
Hello @gustavosarmento . Try to start it from shell. You will get more info there what fails. Possible a missing library. Also, try to enable NoGuiGfx from tooltypes. Remove the parenthesis around it.

**Comment by gustavosarmento** [comment]
From shell, it said that I needed TexEditor.mcc v15 or greater. I had v15.55 (latest from github). Got an earlier version (the latest one in Aminet), now this error doesn't occur, but now I start iGame, some disk access and memory consumption can be observed, but then nothing. No error, even starting from shell (and it doesn't return to prompt).

**Comment by walkero-gr** [comment]
Thank you @gustavosarmento for your message and your help to track where the problem is.
Try to disable from tootypes GuiGfx and screenshot, which will disable the screenshots at the right. If that doesn't help, please have a look at the guide file and check you have all the necessary software and libraries installed.

**Comment by gustavosarmento** [comment]
Enabling the NOSCREENSHOT tooltype did the trick! Maybe some limitation of a plain 68000 system?

Thanks!

**Comment by walkero-gr** [comment]
If your Amiga has a 68000 CPU make sure that the libraries you have installed support it, i.e. there is a different MCC_TextEditor package for this processor. The same applies on CPUs that do not have FPU.
