### ISSUE TITLE
Bug: Can't open menu when set "Enable embedded menu bar"

### ISSUE THREAD

**Issue by samo79** [MrZammler/iGame#144]
Menu does not seems to work anymore in iGame if you set "Enable embedded menu bar" from MUI prefs ... options are showed in the main window but they can't be opened

Tested with iGame 2.1 Beta 1 under AmigaOS 4.1 FE (latest MUI 5.0)

**Comment by walkero-gr** [comment]
@samo79 I checked v2.0b8 and this issue exists there as well. Do you know if there was a version where the embedded menus worked fine.
I will work on a fix.

**Comment by samo79** [comment]
I don't really know, probably that embedded menu never worked in iGame

**Comment by walkero-gr** [comment]
Weird. I just tried it under 3.1.4 with MUI 5 and it works fine. Hmmmm....

**Comment by samo79** [comment]
You may try reporting the eventual issue to Thore

https://github.com/amiga-mui/muidev

If not a bug atleast he may explain us what's up with menus

**Comment by walkero-gr** [comment]
@samo79 Thanks for opening that ticket at mui repo.

**Comment by samo79** [comment]
And you can close the ticket as bug was fixed starting from the latest nightly build :-)

https://github.com/amiga-mui/muidev/files/6194883/MUI-5.0-20210324-0d266f2-os4.zip

**Comment by walkero-gr** [comment]
This is a MUI bug.
