### ISSUE TITLE
iGame doesn't launch game when started from workbench, only from shell

### ISSUE THREAD

**Issue by marcelammerlaan** [MrZammler/iGame#157]
When double-clicking a game, I get a message saying it's saving the gamelist. However the popup for WHDLoad does not appear when I start iGame from the workbench. When I start it from a Shell, I get the same message in the footer of IGame, followed by a WHDLoad popup. This is using the latest beta release. Are there any ways to help debug this?

**Comment by walkero-gr** [comment]
@marcelammerlaan Thank you very much for your message. Sorry for my late reply here. 
This happens with any of the games you have in the list or with a few only? 
The games start fine if you double click on their icon?

Try to run snoopdos before you run the game from iGame. This will report if something is missing.
you can attach here the report so I can have a look.

**Comment by walkero-gr** [comment]
@marcelammerlaan A few days ago I released a new version of iGame. Can you please check this one with your setup and let me know how it works?

**Comment by walkero-gr** [comment]
This should be fixed in [2.3.0](https://github.com/MrZammler/iGame/releases/tag/v2.3.0) release and above. If not, please reopen this ticket
