### ISSUE TITLE
Add joystick navigation

### ISSUE THREAD

**Issue by midwan** [MrZammler/iGame#16]
We should add joystick navigation (e.g. joystick up/down and Fire launches a game)

**Comment by MrZammler** [comment]
This would be nice.

I had some code on a side project (iGameLight, that would be like x-bench, but never got around to make anything usefull - I'll uploade the source), but had joystick support. Left/right would go through the letters and up/down the list.

**Comment by midwan** [comment]
@MrZammler 
That sounds great! We should be able to re-use parts of that, I guess.
Was that also MUI-based?

**Comment by midwan** [comment]
@MrZammler 
Did you use a system-friendly way to detect joystick input?
I was looking at `lowlevel.library` as one approach, but I'm not very excited about the way it does it (constantly polling). I was wondering if there's a better way...

**Comment by wepl** [comment]
AFAIK you can use gameport.device to get input events. But lowlevel.library is probably simpler to implement.

**Comment by MrZammler** [comment]
Yes, I used the gameport.device to get events. I've uploaded the scrap source from iGameLite here: https://github.com/MrZammler/iGameLite

**Comment by midwan** [comment]
@wepl thanks for the suggestion
@MrZammler great, that will help a lot to implement this! Thanks!
