### ISSUE TITLE
iGame fails to parse tooltypes without quotes

### ISSUE THREAD

**Issue by TuKo1982** [MrZammler/iGame#181]
I use custom WHDLoad scripts into game tooltypes and facing an issue where iGame is not able to parse some of them.

i.e.
1) ExecutePostDisk=Execute S:SomeScript 
--> game does launch from WB and tooltype gets correctly read --> this is correct WHDLoad behavior
--> game _doesn't_ launch from iGame

2) ExecutePostDisk="Execute S:SomeScript"
--> game does launch from WB _but_ tooltype gets ignored
--> game does launch from iGame _but_ tooltype gets ignored

Is that something that you could fix in iGame ?
Or could you point me at the right places in sources to fix it ?

**Comment by walkero-gr** [comment]
@TuKo1982 Sorry for my late reply. I think I know why this happens and how to solve it. My question is why do you have that script set in the games and not in the whdload scripts under S: folder? If you did that there this would be applied on all whdload games and demos. And it would work no matter where you launch them from.

**Comment by TuKo1982** [comment]
Hi !

Because I want better granularity than an overall script. On V4, we are able to zoom, enable or disable scanlines and so.

Willem did provide a pull request for a working (tested) fix for it.

https://github.com/walkero-gr/iGame/pull/39

**Comment by TuKo1982** [comment]
Confirmed ! Many thanks for the quick handling of PR and release.

**Comment by walkero-gr** [comment]
Have fun with it
