### ISSUE TITLE
Recoverable alert when closing iGame 2.2.1 (clean install)

### ISSUE THREAD

**Issue by sananaman** [MrZammler/iGame#189]
The latest version iGame 2.2.1 ends up in a recoverable alert when closing iGame.
Most of the times it ends up in a very unstable system and hard reset.
The issue evolves around (not having) screenshots in the game folder.

To reproduce the issue:

1. Copy iGame from the archive into a separate folder. I use DH2:Games/iGame-v2.2.1
2. I use the iGame 060 version (although I tested the 68000 version, it had the same issue)
3. Start iGame
4. Close iGame using the close caption
5. Recoverable alert appears, this time it is recoverable

Note: when I tick the "Screenshots" checkbox, the recoverable alert is gone.

[iGame-SnoopDos.log](https://github.com/MrZammler/iGame/files/10783262/iGame-SnoopDos.log)

----

SYSTEM CONFIG:
iGame Icon Toolips (default):
CLI
DONOTPROMPT

Workbench 3.1
Kickstart 3.2.1
iGame 2.2.1

Hardware: I use an A1200 with Blizzard 1260

I use screenshots of 256x128, that is a nice size for
a standard Amiga workbench interface (640x256).

**Comment by walkero-gr** [comment]
@sananaman A few days ago I released a new version of iGame. Can you please check this one with your setup and let me know how it works?

**Comment by walkero-gr** [comment]
Please test also [2.3.2](https://github.com/MrZammler/iGame/releases/tag/v2.3.2). If this is still happening, please reopen this ticket.
