### ISSUE TITLE
The custom image size is incorrectly stored in iGame 2.2.1

### ISSUE THREAD

**Issue by sananaman** [MrZammler/iGame#190]
When using a custom image for the screenshots, the property is incorrectly saved in the config.
As a result it is not properly reflecting in the user interface and it is not sure what it does in your memory space.

Reproduction path custom screenshot size:
1. Go to settings and untick Hide Screenshots. Leave No GuiGFX on (ticked).

2. Select from the drop-down Screenshot Size "Cutom". Enter Width: 256 and Height: 128

3. Close the window by clicking "Save"

4. Close iGame using the close caption

5. Open iGame again and go to preferences. Here you find a weird number in the custom Width and Height.

6. Check the iGame prefs file you will find something like this:

igame.prefs :
no_guigfx=1
filter_use_enter=1
hide_side_panel=0
start_with_favorites=0
save_stats_on_exit=1
no_smart_spaces=0
titles_from_dirs=1
hide_screenshots=0
screenshot_width=2016459684
screenshot_height=2016460964

While you expect something like this:
screenshot_width=256
screenshot_height=128

Note:
Why would you have a tickbox for something to hide "Hide Screenshots" (some kind of double negative).
I would suggest to turn it around and use "Show Screenshots"  and that should be ticked to use it.

----

SYSTEM CONFIG:
iGame Icon Toolips (default):
CLI
DONOTPROMPT

Workbench 3.1
Kickstart 3.2.1
iGame 2.2.1

Hardware: I use an A1200 with Blizzard 1260

I use screenshots of 256x128, that is a nice size for
a standard Amiga workbench interface (640x256).

**Comment by walkero-gr** [comment]
Fixed in the release [2.3.2](https://github.com/MrZammler/iGame/releases/tag/v2.3.2)
