### ISSUE TITLE
Failed Return code 10

### ISSUE THREAD

**Issue by pawelomega** [MrZammler/iGame#191]
Hi.After installing picasso 3.3.3 or Apollo SAGA drivers under my Coffin R62 when want launch IGAME then system report Failed Return Code 10 and have no idea what to do?

**Comment by walkero-gr** [comment]
@pawelomega Thank you for your message. Please disable the GuiGfx from the configuration file.
There is a discussion about that on EAB (http://eab.abime.net/showthread.php?p=1604049#post1604049)

**Comment by pawelomega** [comment]
Thankyou

**Comment by MrZammler** [comment]
I knew the disable guigfx option would come in handy :-) I do remember even a long time ago, it did have issues sometimes...

@walkero-gr maybe we can get rid of it once and for all? Without it I think we lose scaling of the image, it uses IIRC datatypes/MUI to render the image if we find a way to scale...

**Comment by walkero-gr** [comment]
@MrZammler I plan to implement the scaling using native processes and the datatypes. This is something I've done before but I need to remember that again.

But now I am refactoring the code a lot for the next release, and I must finish this first before doing anything else.
