### ISSUE TITLE
iGame 2.2.1 crashes when scanning for a lot of new games 

### ISSUE THREAD

**Issue by vaskag** [MrZammler/iGame#193]
I have an A500 with pistorm and caffeineOS. When scanning for additional games ( a lot) igame crashes. I tried the same in winuae, and emulator crashes and closes. Is there a limit to the files being scanned? I will try less and see what happens.

**Comment by walkero-gr** [comment]
@vaskag Thank you so much for taking the time to report this issue you experience and I am sorry for that.
Can you please let me know the following?

1. I have tested iGame with more than 2500 games. How many WHDLoad games do you have in your setup?
2. Which version of iGame are you using?
3. Is it possible to attach the winuae config here?
4. Which compilation of games are you using, if any?
5. Which version of OS are you using?
6. Is your setup based on some kind of distribution with everything ready and installed, like caffeineOS?

**Comment by vaskag** [comment]
Thank you for your response. 
1. I tried to import all the whdload gallery at once, except from AGA, CD32 and CDTV. Arounds 4000 files.
2. 2.2.1
3. I test it on real hardware. Amiga 500 with memory expansion and PiStorm
4. All
5. CaffeineOS Storm v918
6. CaffeineOS Storm v918

I tried importing smaller batches of games with no problem.

**Comment by walkero-gr** [comment]
@vaskag A few days ago I released a new version of iGame. Can you please check this one with your setup and let me know how it works?

**Comment by vaskag** [comment]
I removed all the games that are not compatible with a500 (aga, cd32, cdtv). The number decreased and the scan completed without errors. with the 2.2.1. Since I am not going to add the non compatible games, is it woth the update to 2.3.1?

**Comment by vaskag** [comment]
I use [WHDLoad-Download-Tool 1.21](https://github.com/MrV2K/WHDLoad-Download-Tool)

**Comment by walkero-gr** [comment]
@vaskag Have you tried the latest versions of iGame and if that issue still occurs? If you do, and you still experience this problem, please feel free to reopen this issue.
