### ISSUE TITLE
Toolchain link is broken

### ISSUE THREAD

**Issue by midwan** [MrZammler/iGame#2]
Hi @MrZammler 
The VBCC toolchain link you have in the Readme (http://winterland.no-ip.org/2014/07/vbcc-cross-compiler/) seems to be broken currently.

There is a thread on EAB with an up-to-date VBCC toolchain installer for Windows: http://eab.abime.net/showthread.php?t=83113&highlight=VBCC although that does not include the MUI includes of course.

**Comment by MrZammler** [comment]
Ah, thanks mid!

Sorry, it was in an older blog system, I've updated the readme with the correct link: http://winterland.no-ip.org/2014/07/12/vbcc-cross-compiler/

(Although, the build there is kinda old, and not sure if it still works....)
