### ISSUE TITLE
igame v2.3.2 hangs when wrong igame.iff resolution is set

### ISSUE THREAD

**Issue by sananaman** [MrZammler/iGame#203]
I use iGame on an A1200 with 1084 monitor. I run 640x256 resolution (the default for the Amiga workbench).
For this I use game screenshots of 256 x 128 then it is nicely 4:3 proper scaled screenshots.

Issue:
When I use iGame clean install v2.3.2 and untick "Hide Screenshots".
By default it is looking for "160x128".

Then when you did scan of my repository, which already contains in every folder the igame.iff (256x128).
Then I click several games and after a view clicks iGame just "hangs" and system needs a reboot.

Fix:
There is a way to fix it: Go to settings enter a custom Screenshot Size of 256 x 128 the problem is gone.

Request:
It has nothing to do with this bug, but please add 256 x 128 to the dropdown menu. That would be very convenient for A1200 users with a classic setup (CRT monitor, 640x256 reso).

**Comment by walkero-gr** [comment]
@sananaman Have you tried the latest versions of iGame? If that issue still remains, please feel free to reopen it.
