### ISSUE TITLE
iGame 2.3.2 Main Menu Icon Scaling.

### ISSUE THREAD

**Issue by Tallguy297** [MrZammler/iGame#204]
Is is possible to have the selected icon in iGame main menu match the selected resolution?

I have quite a few games that do not have a game.iff file.
The games that do have a game.iff file, the resolution is set to 320 x 256 and the main menu displays nicely on an RTG screen.
However games without a game.iff display the icon in it's original pixel size.

Thank you...

**Comment by walkero-gr** [comment]
@Tallguy297 
Thank you so much for your message. The way to do it is to enable the GuiGfx library by unchecking the "No GuiGfx" checkbox in the preferences. This requires a proper installation of 2/3 libraries, the guigfx.library, the render.library and the MCC_GuiGfx. MUI 5 comes with all of them in the archive, but if you use MUI 3.8 then you have to install them. You can find them on Aminet.

The versions I use are:
MCC_GuiGfx v21.7
guigfx.library v20.0
render.library v40.8

If one of the above libraries is missing the "No GuiGfx" checkbox is going to be blocked.

**Comment by Tallguy297** [comment]
I have double checked the versions as your stated, and they are the same as in in the MUI 5 archive.
If I uncheck the No GuiGfx option, the program does not open.

![iGame](https://user-images.githubusercontent.com/49935683/235427261-2d0bc7c3-1373-4ec2-a6ef-b67c8188c0a0.jpg)

Thank you...

**Comment by walkero-gr** [comment]
I guess you are using the latest v2.3.2, right?

**Comment by Tallguy297** [comment]
Yes, that is correct.

**Comment by walkero-gr** [comment]
From the screenshot I see that you emulate an A600. Which CPU do you use for that? If it is a 68000 then you need to use versions of these libraries that work with that CPU.
The reason why iGame doesn't start is that the GuiGfx library fails to open.

**Comment by Tallguy297** [comment]
I have an Amiga 600 with a Apollo MantiCore accelerator card running Workbench 3.2.2.1
I get the same result on my real Amiga.

I thought this problem I am having could be related to the datatypes?

**Comment by walkero-gr** [comment]
> I thought this problem I am having could be related to the datatypes?

I do not believe this is because of datatypes because datatypes are used to show the screenshot if you do not use GuiGfx, and those display just fine on your system.

If you open the MUI folder where this is installed, there is a Demos folder and inside that there is a Guigfx demo app. Does that work when you run it? If yes, then maybe for some reason iGame fails on your setup, which I need to investigate further. If not then there is an incompatibility on your system that break GuiGfx library.
Please, have this tested because it will help us understand the problem.

**Comment by Tallguy297** [comment]
I have tested the GuiGFX demo and it works very well.

I changed the render.library and guigfx.library to the non-fpu versions and it didn't make any difference.
I still can't open iGame 2.3.2 with the noGui GFX option unchecked.
I put the render.library and guigfx.library from the MUI archive back on and the same thing as above.

FYI, I have WinUAE emulating an Amiga 600 with 68020 CPU + 68882 FPU, which is similar to my real Amiga.
The reason I am using WinUAE at the present is it is easier to test and download files to correct software problems.

Regards,
Alex.

**Comment by Tallguy297** [comment]
I have attached 2 logs from SnoopDOS.
Perhaps they might give some insight as to what I am doing wrong?

This is when iGame is working and the NOGUI GFX option is checked.
[WORKING.log](https://github.com/MrZammler/iGame/files/11364579/WORKING.log)

This is when iGame is not working and the NOGUI GFX option is unchecked.
[NOTWORKING.log](https://github.com/MrZammler/iGame/files/11364581/NOTWORKING.log)

I hope this information is helpful?

Thanks...

**Comment by Tallguy297** [comment]
This is the error I receive with I run the game with the No GuiGFX unchecked.

![iGame Error](https://user-images.githubusercontent.com/49935683/235451213-16c8d27c-5bd8-43ed-8d65-f54ba2a9bfeb.jpg)

Thank you...

**Comment by walkero-gr** [comment]
not so helpful, right? At least it is not from the checks iGame does on the libraries

**Comment by Tallguy297** [comment]
Do you know where the error routine is located in the source code?
It might give me some idea why the program is crashing.

Thank you...

**Comment by Tallguy297** [comment]
I've done a clean install of Workbench 3.2.,2, install MUI 5.0 and iGame.
Works perfectly with NoGuiGFX option checked or not checked.
However that does not solve my problem.
I must have another library conflicting with iGame to give the error 10 when I start iGame with the No GuiGFX option unchecked.
Any idea why the program fails with an error code 10?

Thank you...

**Comment by Tallguy297** [comment]
I solved the problem.
It is the Picasso96 3.3.3 Prosac drivers.
I had to degrade to the Picasso96 3.3.2 Prosac drivers and the problem has disappeared.

Thank you...

**Comment by walkero-gr** [comment]
@Tallguy297 Yeah, there is a bug there that is mentioned at https://github.com/MrZammler/iGame/issues/191 as well.
Thank you for letting us know.
