### ISSUE TITLE
Selecting properties crash

### ISSUE THREAD

**Issue by samo790** [MrZammler/iGame#209]
iGame will crash if you select the properties option from menu while no item/game are selected

Crash is reproducible with latest iGame 2.4.0 under AmigaOS4

[Crashlog_iGame.OS4_2023-05-14_19-16-52_seleziona_proprietà.txt](https://github.com/MrZammler/iGame/files/11472858/Crashlog_iGame.OS4_2023-05-14_19-16-52_seleziona_proprieta.txt)

**Comment by walkero-gr** [comment]
@samo790 I had a look at that and found some hits. I have already a fix for that, which will be available in the next release.

**Comment by samo790** [comment]
Ok good, as a side note i found a minor issue with the error window... the "ok" button does not support the shortcut there :-)
I have added an underscore to the ok string, but it's not picked there, perhaps you may fix it as you are here ;-)
