### ISSUE TITLE
Update catalog for iGame 2.4.0

### ISSUE THREAD

**Issue by samo790** [MrZammler/iGame#210]
Updated italian catalog attached, please merge :-)

[igame_ita.zip](https://github.com/MrZammler/iGame/files/11472860/igame_ita.zip)

**Comment by walkero-gr** [comment]
Thank you so much for this. It will be included in the next release

We have a group for all the translators of iGame at https://groups.io/g/igame-translators
If you want to get updates before the releases, please subscribe there.

**Comment by samo790** [comment]
Ok noted ;-)
