### ISSUE TITLE
Scanning Repositories

### ISSUE THREAD

**Issue by shan2752** [MrZammler/iGame#215]
Hi, I deleted my former .csv database, added mirv2k’s igame.dat sets, and rescanned the repository.  Everything looked good.  I had to work through some extraneous listings and then rescanned, but the update reverted back to the directory names rather than the igame.dat files.  I have the prefer igame.dat check box checked in settings.

It’s cumbersome to have to reselect favorites anytime I have to delete the .csv database.  Maybe there’s an option to have a separate database for favorites just in case updates mess up the main database?  Thanks!

**Comment by walkero-gr** [comment]
Unfortunately, I can't reproduce it here. Please make sure that the setting didn't change and that you still have the igame.data preferred. 

Right now iGame doesn't support updating an existing gameslist with extra data. This is something that I have on my todo list. You see, the gameslist changed a lot with the new versions and a new rescan is mandatory now that the igame.data files are used.

I will investigate more in case I manage to reproduce the problem you mentioned.

**Comment by gustavosarmento** [comment]
Confirming that it still happens with 2023-09-24 beta. Steps to reproduce:
- delete gameslist.csv if present;
- confirm "prefer igame.data" is selected on prefs;
- scan repositories. After finished, indeed the names are from the igame.data files;
- go to prefs again to check if "prefer igame.data" is still selected (it is);
- "scan repositories" again. After finished, the names are taken from the directories, even with "prefer igame.data" still selected.

**Comment by walkero-gr** [comment]
Please, give a test of the new v2.4.5 and let me know if this issue is resolved

**Comment by gustavosarmento** [comment]
Hi George,

I’m on vacation right now, and won’t return until the 8th.

Guess I’ll have to pass this test, unfortunately.

Regards,

Em sex., 3 de nov. de 2023 às 16:08, George Sokianos <
***@***.***> escreveu:

**Comment by gustavosarmento** [comment]
Just tried it, and the problem is indeed gone!

Well done!

**Comment by walkero-gr** [comment]
@gustavosarmento Thank you so much for testing it.
