### ISSUE TITLE
Strange behaviour: Game start loop

### ISSUE THREAD

**Issue by RamsesUTL** [MrZammler/iGame#219]
I have some really strange behaviour with iGame on my system.
When I'm starting a game from the list (pressing enter or double click), the game starts and works perfect. But when I quit the game with the WHDLoad given key, the game (or whatever is then actual selected in the list) directly starts again. I quit, it starts ...
Even if I'm closing iGame (in the short time I see my system) and start it again, it immediately tries to start a game (the top one of the actual list). Because my favourites are empty, I get "Please select an entry from the list" over and over.
If I quit iGame my system works just fine otherwise, but I need to do a reset to do anything in iGame again.
Any idea what might be causing this (maybe something in my system) and how to stop this?

**Comment by RamsesUTL** [comment]
Amiga 2000, GVP 68030 with 16MB, Amiga OS 3.1.4, Kickstart 46.143 and a lot of patches and tweaks installed

**Comment by walkero-gr** [comment]
@RamsesUTL I am sorry for the late reply. I would like to know which game is it and where can I find it. Is it included in any game collection? Which version of iGame do you use?

**Comment by RamsesUTL** [comment]
@walkero-gr Thanks for taking your time for my strange problem!
It's not a specific game, it happens with all of the items. The moment I quit a game or demo iGame automatically starts the actual selected item again. If I manage to select another item in that short time I see the desktop that item starts next time.
Even if no item is selected (after I quit and restart iGame of if I choose an empty genre) iGame tries to start an item ("Please select an entry from the list"). Like iGame is stuck on that action and does it again and again.
Yesterday evening I tried iGame 2.4, 2.1 and 2.0 (the 68030 versions) all with the same result. I even disabled most of the patches in my system (I use MCP for a lot of that) but nothing changed. I suspect that MUI maybe has something to do with it, but can't figure out what it is and how to fix this. Everything else in my system works just fine.
If you are still not sure what I mean, I can provide a video if you like.

**Comment by RamsesUTL** [comment]
@walkero-gr You might be on to something. I use MuFastRom but I disabled it for tests and nothing changed. I'll attach you an archive with my startup files. In WBStartup I have FreeWheel, RTPatch and ToolManager.

**Comment by walkero-gr** [comment]
@RamsesUTL I saw a message on Facebook by someone who has similar gear to yours describing the same issue. He wrote that when he disables MuFastRom he doesn't have those issues anymore, but his system gets slow.
For a couple of weeks, I am away from my dev computer. As soon as I get back I will try to reproduce the problem and if possible solve it.

**Comment by RamsesUTL** [comment]
Thanks for looking into this and take your time.

**Comment by walkero-gr** [comment]
@RamsesUTL I had a chance today to have a look at the problem you described. I downloaded the latest MMULib and installed the Mu patches that you have as well. Unfortunately, I couldn't reproduce the problem. Maybe some other patch or a combination of patches makes your system behave like that. I would suggest you try to disable one by one the patches and see how it behaves and if you still have the problem. This way you will find faster the issue.

Please let me know if you have any news on that.

**Comment by RamsesUTL** [comment]
First thank you for trying a few things out, I appreciate this!
I finally found time to give my Amiga some love. Updated to iGame 2.4.4 and tried to disable one by one everyting that I could think of to interfear. Sadly I achieved nothing, it's still the same behaviour for me. I'm know thinking to do a clean system install on a free partition with only MUI, WHDLoad and iGame on it, just to see if that changes anything for me on that machine.
The one new thing I noticed is that I can't open the game properties for selected games. Nothing happens if I select them in the menu or use the short cut.

**Comment by RamsesUTL** [comment]
Just saw that someone else also had a problem with the game properties shortcut.
https://github.com/MrZammler/iGame/issues/213
I'll try your suggested fix in the next days. Strange thing is that for me the properties not even open over the menu.

**Comment by walkero-gr** [comment]
@RamsesUTL 
A few days ago I had a fix on that issue. Please have a look at https://github.com/MrZammler/iGame/pull/229 where you will find a testing version that, I hope to solve that issue. Please test it and let me know how it works.

**Comment by walkero-gr** [comment]
@RamsesUTL Did you have time to test the latest version? If you do and this problem continues to occur, please reopen this issue.
