### ISSUE TITLE
Rescanning repositories causes gamelist.csv corruption

### ISSUE THREAD

**Issue by MrV2K** [MrZammler/iGame#222]
IGame version 2.4.1.

If you rescan your repositories, the gamelist corrupts. If you delete the gamelist and do a fresh scan it's fine. I've attached two csv files. The first one is the original. The second one was rescanned immediately after and is corrupted. Both were generated using my data files. The problem also causes a guru/crash.

**Gamelists**
https://mega.nz/file/DccGxRxC#RtYAhi-RpfG1bUIMZbUphaEYn392oR8N9KqKDEgNryA

**IGame data files**
https://mega.nz/file/zYdEAIZQ#pybqCpE9XhuoPg9ZietNe3RUkWgPwg26fWGfhYIfjOQ

![image](https://github.com/MrZammler/iGame/assets/71010565/0b9eacd6-e81c-441d-a6ff-c122335aca1c)

**Comment by walkero-gr** [comment]
@MrV2K 
Thank you so much for your message. I had a look in the gameslist.csv file and it seems it added 2 lines at the start that have info from games that exist in the list again. I will try to replicate why this happened and will let you know.

**Comment by MrV2K** [comment]
Still the same problem in v2.4.3
[GamesLists.zip](https://github.com/MrZammler/iGame/files/12503339/GamesLists.zip)

**Comment by DFXThomas** [comment]
I just tried iGame again after re-installing my WInUAE Amiga setup. There's still the same issue. Existing game entries get corrupted when clicking on "Scan repository". Broken genre entries are being created. WTF?!

**Comment by walkero-gr** [comment]
@MrV2K 
Can you please try again with the v2.4.4 https://github.com/MrZammler/iGame/releases/tag/v2.4.4 and let me know if that's better?

**Comment by DFXThomas** [comment]
Seems to be working fine now, with v2.4.4. Thank you!
