### ISSUE TITLE
Option to skip re-saving list every time you launch a game

### ISSUE THREAD

**Issue by midwan** [MrZammler/iGame#23]
This already exists as a tooltype, but perhaps we should have a Settings window with it (and other settings)?

Optionally skip re-saving the list every time you launch a game, to reduce tear and wear of flash media.

**Comment by MrZammler** [comment]
Ok, so there is a tooltype for this. From the Guide:

"SAVESTATSONEXIT: Use this tooltype to let iGame know you don't need
saving your games statistics each time a game is launched. Instead it will save them when
you quit iGame. Of course this implies that if a game crashes and the amiga is rebooted,
statistics are lost."

This specific issue could be closed, maybe we should open one for a general settings window?

**Comment by midwan** [comment]
I think it would be best to have a dedicated "Settings" window, where the multiple options can be configured easily (using the GUI). Tooltypes are nice also, but when they start piling up they can get hard to configure.

Maybe it's best to leave these open, so we can implement them one at a time in a new Settings window?
As soon as one (or more) is implemented, we can close it.
That way, if something takes more time, it doesn't have to delay the whole effort - there could be intermediate versions with the settings window and not all features added to it.

**Comment by midwan** [comment]
On second thought, since we're documenting the Tooltypes on the Wiki as we go also, I think we can close this.

We'll handle the Settings window as a separate issue.
