### ISSUE TITLE
Edit Properties doesn't work

### ISSUE THREAD

**Issue by nujack74** [MrZammler/iGame#231]
I still try to find the root-cause why I'm not able to edit properties in iGame 2.4.4 (2023-09-11). When I select "Game Properties" the Window is opening but I can't change the Genre (only "Unknown" is availble). Furthermore I can't modify the Tooltypes (field can't be edited). I've updated all my libraries but it doesn't solve the propblem. These libraries are in usage:

guigfx.mcc = 19.2
texteditor.mcc = 15.53
render.library = 32.0
guigfx.library = 20.1

I use the program on my A500 with TK68EC020 and 8MB Fast under AmigaOS 3.1.
Any help welcome. Thank you.

![IMG_5012_small](https://github.com/MrZammler/iGame/assets/65897800/041b0893-b145-4877-b25a-88b7ba5f2dcd)

**Comment by walkero-gr** [comment]
@nujack74 I am sorry you have that issue. Can you please let me know what version of icon.library do you have in your system?
Since iGame v2.3.0 I changed the way that work. In the release I have the following comment:
> Now iGame requires icon.library v44+ for changing icon tooltypes. For systems that do include a new version, there is icon.library 46.4 on Aminet is free to download and use. Those that have older versions of the library will still be able to use iGame, but they won't be able to change the icon tooltypes. They will need to do it from Workbench

**Comment by nujack74** [comment]
Issue can be closed. 
I'm now running with icon.library 51.4 and can edit the Tooltypes in iGame 2.4.4. Before I used icon.library 40.1 from Kickstart-ROM.
I can change the Genre too but have to disable "Hide side panel" in the settings first. When side-panel is hidden, you can't change the Genre. Not sure if that's a bug or feature.

**Comment by nujack74** [comment]
Not working with icon.library 40.1 from Kickstart-ROM.
