### ISSUE TITLE
GUI improvements and new features

### ISSUE THREAD

**Issue by midwan** [MrZammler/iGame#25]
Some menu options that would be useful:
- Duplicate (done with 071005d9b484deccdb8ac3768af41e1557e7f6ab)
- Delete (Done with b2a8e61c4822f06171aab05d83b6129aa5cb5d2a)
- Open List (Done with 8f49428cd2b73b06f5ffc38211a0a7b60fca2c22 and 0f2dfa67b9d4ca2e1c833f9ff7ee656e16ca929b)
- Save List (done as of b2a8e61c4822f06171aab05d83b6129aa5cb5d2a)
- Save List As... (Done with 8f49428cd2b73b06f5ffc38211a0a7b60fca2c22 and 0f2dfa67b9d4ca2e1c833f9ff7ee656e16ca929b)
- Export List to Text file - Won't implement, not much use (the gameslist is already a text file)

**Comment by midwan** [comment]
I think we can combine this with a total GUI overhaul, where needed, so I've updated the title.

Regarding the Menu items, I've designed this so far:
![igamemenu](https://user-images.githubusercontent.com/3877365/44049706-24734c30-9f35-11e8-8626-a832ec615fe0.png)

Explanation:
A **File** menu is more standardized and expected in most applications, when dealing with Files. Since iGame does deal with files, I think it would make more sense to have file-related operations under that.
- I've added a few options under File, that I imagine users would find useful (I know I would!). Those are 
- **Open List** (to open a custom GamesList, by opening a File Requester), 
- **Save List** (to manually re-save the List), 
- **Save List As** (self-explanatory), 
- **Export List to a Text File** (to export only the game titles/or slave paths to a trimmed down text file)

I've added an **Edit** menu, which contains the following:
- Copy (to copy the selected entry)
- Paste as New (to create a new entry by pasting the previously copied entry) - Perhaps we can merge these two into one function, named Clone Entry?
- Delete (to Delete the selected Game Entry from the List). Maybe we can offer additional options here, to delete actual files from the filesystem as well?
- Properties (this opens the known Game Properties Window. It makes more sense to me to relocate this here, since we're Editing one of the entries in the List).

Finally, the **Settings** menu contains:
- Settings (to open a new window, where iGame preferences can be set, and saved to a file. This is usually easier to manage than editing Tooltypes).
- Game Repositories (to open the existing Game Repositories window. I think it makes more sense to relocate this under Settings, as is it is essentially a configuration option).


Regarding the GUI elements, I've also made some improvements, as follows.

Existing Properties Window:
![igameproperties](https://user-images.githubusercontent.com/3877365/44050357-01193612-9f37-11e8-935e-5529141f0a53.png)

New version I designed:
![igameproperties-2](https://user-images.githubusercontent.com/3877365/44050485-588c733c-9f37-11e8-88b3-041a6f23e1ca.png)

(Ignore the Tooltypes control, it's currently just a textbox but it will eventually be a TextEditor like the original)
I think this layout is a bit better, with Labels in place for the `Times Played:` and `Slave Path:`. I also like the vertical arrangement a bit more, since it doesn't waste much space on-screen if you want to see the Tooltypes.


Existing "Add non WHDLoad game" window:
![igameadd](https://user-images.githubusercontent.com/3877365/44050670-faf9c174-9f37-11e8-8eb8-ea62d8657562.png)

New version I designed:
![igameadd-2](https://user-images.githubusercontent.com/3877365/44050681-02b2d3a6-9f38-11e8-964f-efe8eb2c241c.png)

I've added Labels next to the controls for clarity, improved the spacing a bit, and added a Genre dropdown as well (I think it would be nice to have that assigned to a game while adding it).


Additionally, I've slightly edited the main window, to add a few pixels of white spacing between the controls, so that it looks better to the eye. The changes are subtle, but they make a difference.

Old version:
![igamemain](https://user-images.githubusercontent.com/3877365/44050971-d8585be8-9f38-11e8-894b-d9ec34892544.png)

New version:
![igamemain-2](https://user-images.githubusercontent.com/3877365/44051011-fe69b962-9f38-11e8-8fcc-3627f8e43b94.png)

Let me know what you think.

**Comment by midwan** [comment]
@MrZammler 
This is the new Settings window I designed, so far:
![igame2 0b-settingswindow](https://user-images.githubusercontent.com/3877365/44298743-c968c880-a2e8-11e8-9e87-547dce1c10e8.png)

What do you think? Should we change something, add something?

**Comment by midwan** [comment]
Updated to this today:
![igame2 0b-settings](https://user-images.githubusercontent.com/3877365/44308817-c808d000-a3bc-11e8-9bfb-dc32354867b8.png)

**Comment by midwan** [comment]
Delete function implemented with b2a8e61c4822f06171aab05d83b6129aa5cb5d2a

**Comment by MrZammler** [comment]
Why a delete function? Isn't hidden enough? Would the deleted game be re-added on the next scan ?

On gui stuff: Make sure they fit on a PAL Hires (640x256) screen. Remember this resolution has much more horizontal space than vertical.

Also the NOGUIGFX should remain as a tooltype.

**Comment by midwan** [comment]
@MrZammler 
The delete function is meant to allow deleting from the gameslist file, on the next save. Entries that have a Delete status, will not get saved when the list is saved back to disk. If you rescan a repository of course, those will be re-added normally.

I will test the GUI windows on PAL HiRes before sending them your way, of course. ;)

All the options shown above exist as tooltypes for the moment, the window is meant to make things easier in managing them. We can decide if we will keep Tooltypes only, both tooltypes & a prefs file, or only the later. Either way, the settings window has its merits I think, as you can easily control everything with a few clicks from here. If in the end we only have Tooltypes as configuration options, the Save button here will update those tooltypes for you.

**Comment by midwan** [comment]
Implemented **Open List** and **Save List As** functionality, with ASL File Requesters for both.
The idea is that you are now able to have multiple gameslist files, and load/save between them as you wish. Only one can be loaded at a time, the list is cleared when opening another.

**Comment by MrZammler** [comment]
By design iGame's list is a 1 to 1 representation of the games installed. As such, I can't see what open/save/copy/delete etc operations are gonna do. There are ways to manipulate the list through genres, hidden items, etc. These change the way iGame thinks of it's list and I need to think about it. We'll pause this for now.

The settings window is nice. We should only keep the settings window, and get rid of the tooltypes. They were just an easy way to change some of iGame's parameters. However, NOGUIGFX should remain as a tooltype (if a setup crashes when opening iGame, there should be a way to enforce NOGUIGFX). It should also be removed from settings.

There should also be a clean way to upgrade from tooltypes to settings. Maybe check on start if no prefs is found, to pick up the tooltypes and convert them to prefs. This operation should be as minimal as possible, so as to not add a lot of delay when starting up.

**Comment by midwan** [comment]
@MrZammler 
Regarding the Settings: I agree, it's best to keep one approach (a prefs file in this case) instead of both.
My idea was to do this as follows:
- During startup, check if there's a Prefs file (we'll have to decide where to search for that, as there could be multiple locations - PROGDIR:, ENV:iGame/, ENVARC:iGame/)
- If a Prefs file was found, we load it and get the settings from there, and proceed to apply them globally (by setting the global variables we already have in place)
- If a Prefs file was NOT found, we can throw a prompt to the user after everything is loaded, notifying them accordingly, and allowing them to proceed with the generation of that (converting Tooltypes to Prefs file) or not.

That way, we don't inject any bigger delays during startup and we delegate the choice to the user, instead of forcing the operation ourselves.

I can move NOGUIGFX to the Tooltypes only again, no problem.

Regarding the Open/Save and Duplicate/Delete functions:
iGame still operates as usual on the "gamelist" it has loaded. Open/Save/Save As just allow you to have more than one such collection (but you can still only have one loaded at a time). 
The change inside iGame is minimal (basically just the functions to load or save the file), the rest operates exactly the same, once the list is loaded. 
For me, this is useful because I can separate out my collections to different files and load the one I want to use. 
E.g. I might want to separate out a collection I have on an external SD card, which I only plug in sometimes, from another smaller one, that I have on my disk. I would like to be able to load the `gameslist` I want from within iGame (which I might have renamed to anything I want also), instead of only loading the `PROGDIR:gamelist` file always. And to maintain separate collections, I need a Save As function accordingly.

The Delete function is useful if you want to get rid of an entry from the file completely, instead of just hiding it. It's not a big difference from Hide, I agree, but it does help getting rid of files that you don't really want in the file - and it makes the file smaller, and therefore faster to load on startup. Sure, you could use a Text editor to hunt down the entries and remove them by hand if you wanted, but why not offer that from within iGame?

Regarding the Duplicate function, it was requested by users on Facebook when I asked for ideas they might have. I personally don't see much use for it either, so I won't insist on it :)

**Comment by midwan** [comment]
Removed Export List menu option with f506df0787babd4b7b00eee56e9f693f41140541

**Comment by midwan** [comment]
Fallback to reading the Tooltypes if no "igames.prefs" file was found, with d515110ba6b8853a749a3ffc5cbd670ed4b78a9a
