### ISSUE TITLE
Not all memory is freed when closing iGame

### ISSUE THREAD

**Issue by midwan** [MrZammler/iGame#41]
I run a few tests, and monitored the free Fast RAM I had before and after running iGame.
The memory was reduced after each run, by a few KB.

We're probably not deallocating something when closing down, will have to look into this.

**Comment by midwan** [comment]
I will have to test this in an isolated environment also, to ensure it's not caused by anything else in my system.

**Comment by walkero-gr** [comment]
This is fixed in version 2.3.0 and above. The rest of memory leak has to do with MUI itself
