### ISSUE TITLE
Save stats on exit

### ISSUE THREAD

**Issue by jonthorell** [MrZammler/iGame#44]
Using iGame 2, beta 2. Was present in beta1 as well.

If "Save stats on exit" is enabled, the gameslist gets wiped upon exit. The file is still there but zero bytes in length.

Reproducable: enable save stats on exit, and close the application. On next startup the gamelist is empty. Happens everytime, at least on my system.

Using A1200, Blizzard 1230, 64 megs ram and PFSAIO-DS as filesystem on a 32gig compact-flash card.

**Comment by midwan** [comment]
@jonthorell 
Thanks for reporting this.

I'll try to recreate it this afternoon and get back to you.

**Comment by midwan** [comment]
@jonthorell 
I cannot recreate this, when following these steps:

- Open iGame v2.0b2
- Open Settings and enable "Save Stats on Exit"
- Close iGame
- The `gameslist` file remains identical
- Re-opened iGame
- Closed iGame again
- The `gameslist` file remains identical

Did you do something else in between perhaps (like launching something from iGame, modifying an entry, etc)?

**Comment by midwan** [comment]
Also, could you please attach the gameslist, genres and repos.prefs files you used?

**Comment by jonthorell** [comment]
Hello,

No, I didn't do anything in between. I just did it again just to make sure and the same thing happens. Or rather: I did it four times. Before it happened all the time, now only only in some. 

Try 1 and 2: I could trigger the bug
Try 3: It complained about not being able to open the gameslist even though it was there (in rw mode)
Try 4: It behaved as you describe above, but after starting a game and going back to the workbench then quitting the program, the gameslist was empty again.

I've attached several files here:

igame_dir1.txt and igame_dir2.txt - output of list in the igame-directory with flags and filesizes available
genres and gameslist as requested
Two prefs files: one with stats enabled and one with it being disabled

I've only added a .txt extension so github won't complain.
[gameslist.txt](https://github.com/MrZammler/iGame/files/2412887/gameslist.txt)
[genres.txt](https://github.com/MrZammler/iGame/files/2412888/genres.txt)
[igame.prefs_1.txt](https://github.com/MrZammler/iGame/files/2412889/igame.prefs_1.txt)
[igame.prefs_2.txt](https://github.com/MrZammler/iGame/files/2412890/igame.prefs_2.txt)
[igame_dir1.txt](https://github.com/MrZammler/iGame/files/2412891/igame_dir1.txt)
[igame_dir2.txt](https://github.com/MrZammler/iGame/files/2412892/igame_dir2.txt)

**Comment by midwan** [comment]
@jonthorell 
Thanks for the files.

I couldn't recreate the problem when using the gameslist and genres you provided, the file was not emptied on multiple start/quit tests.

I noticed something interesting in your prefs files however:
- screenshot_width and screenshot_height have very large (and probably invalid) values. They are also different between the two files.

Normally you should have a valid screenshot width and height there, as selected by the Settings window. Some valid values would be 320x256, 160x128 or a custom typed value as well.

Did you select any screenshot width/height in the Settings when you saved them?

**Comment by jonthorell** [comment]
Strange. I'll take a look and see if I can find something else in say s:user-startup or something that may cause the problem then.

As far as the screenshot_width and height goes, Ive never touched those settings. Neither in the old 1.6 something version by tooltypes or the new version. I also saw the strange values but forgot to mention them.

**Comment by midwan** [comment]
@jonthorell 
It might be worth checking if it's a flash media problem as well. If possible, could you try with another card?

**Comment by midwan** [comment]
Just tested it on a real A4000, with PFS AIO running on a Sandisk CF card as well.
No problem found in all the tests I've made.

**Comment by jonthorell** [comment]
Sorry for the late answer. Anyhow, I have not been able to pinpoint where the problem is on my system except that we can rule out the card. I have tried on three different ones with the same result. And with a very bare-bones startup as well, but the problem persists.

However, if I enable the setting and then replacing the empty gameslist with a proper one from backup and do not change the settings again there is no problem. Then it works as it should.

As long as no one else can duplicate my problem then I think it is safe to say there is something on my system that interferes, even though I haven't found what. At least not yet.

**Comment by midwan** [comment]
@jonthorell 
Then it might be something in the gameslist file itself? Although I tested with the ones you posted above, and I couldn't recreate the problem there either...

Nobody else has reported something like this (at least, not yet), so I'm pretty sure it's isolated to you in this case. I'll keep an eye out of course, just in case.

**Comment by MrZammler** [comment]
Hi,

I'll try and do some test here as well, and see if I can catch something.

**Comment by walkero-gr** [comment]
This was not reported by anyone else all these years.
