### ISSUE TITLE
Path= in config list getting wiped

### ISSUE THREAD

**Issue by IvanEBC** [MrZammler/iGame#45]
Upgrading from a well organised previous version to the new 2 beta2.

Load igame-060, configured and running, but all genres are listed, but empty. Check many games, all are listed as "unknown" despite the gamelist.txt still showing the correct genre. I change one of the genres to the correct one, check the genre and it appears, can even run it. Close igame, check the gamelist.txt, there's a carriage return inserted, ok ... as long as it works, but when i load igame next... the "path=" field has been wiped during the loading... so the game won't load, and the screenshot will not display.... all files on Amiga are still in place, but the gamelist.txt is altered and saved and now busted.
Thanks.

**Comment by midwan** [comment]
@IvanEBC 
Thanks for reporting this.
Could you provide a copy of your gameslist before and after the effect? That would help understand what happened.

**Comment by IvanEBC** [comment]
OK... attached is .....
**"gamelist.txt-b4"**
This was the list pretty much imported from the old 1.6 directory...... i then run igame2 
Top entry shows a demo called "Nude" by Puzzle... it shows the genre=Puzzle. My genres has an entry called Puzzle and the list of genres does appear, but selecting Puzzle in igame, appears empty.

I click the properties of Nude and change the genre from "unknown" to "puzzle"
check igame genres, Nude appears under the Puzzle Genre, i exit igame.
Attached is **"gamelist.txt-edit"** where at the bottom of the text file shows the saved fixed version, but it has this extra spare line..... but i figure, meh, if it works!!!

I load up igame again. 
Nothing under the puzzle genre and no screenshot, and won't run, check gamelist.txt again (which is attached as **"gamelist-final"** and the path= has now been wiped. This happened during the LOADING phase of igame.
In terms of prefs, only thing turned on is Save Stats on Exit.

PS: .txt added to gamelist .. otherwise github wouldn't attach the files.

[gameslist-b4.txt](https://github.com/MrZammler/iGame/files/2411543/gameslist-b4.txt)
[gameslist-edit.txt](https://github.com/MrZammler/iGame/files/2411544/gameslist-edit.txt)
[gameslist-final.txt](https://github.com/MrZammler/iGame/files/2411545/gameslist-final.txt)

**Comment by midwan** [comment]
@IvanEBC 
Thanks. So the problem in the gameslist file occurred when you set the Genre (because it wasn't detected) and it got saved back to disk.

Interestingly, this is one of the bugs the beta2 was supposed to fix, specifically with b702625526d3b737f22ed02e771cf326b58a6b3f - Did you test this with the beta2 from scratch also?

Regarding the Genres list, the only thing changed is that the empty line at the end is removed (which is OK). They should had been detected when you selected "Puzzle" of course.

I'll test things with theses files and get back to you.

**Comment by midwan** [comment]
@IvanEBC 
Hmm, I can't recreate the problem, when using your files and beta2:

- I copied the gameslist-b4.txt as `gameslist` in the iGame PROGDIR:
- I copied your genres-before.txt as `genres` in the iGame PROGDIR:
- Launched iGame v2.0b2
- Clicked on Puzzle genre, and I saw that 2 entries were shown after the filter was applied:
![igame2-genretest](https://user-images.githubusercontent.com/3877365/45970944-1bafae80-c038-11e8-90b7-97c6aff0949d.png)

Considering also that there was this bugfix in beta2, I suspect you run into the bug from beta1, but didn't test from the beginning with beta2?

**Comment by midwan** [comment]
@IvanEBC 
Thanks for confirming.

Paths that contain spaces should of course be possible to be used, so I'll look into that.

**Comment by midwan** [comment]
@IvanEBC 
I can't recreate the problem with spaces either I'm afraid.
I tried having directories with spaces, which contained other directories with spaces, which contained the slave files.
It seems to work for me.

Could you give me some specific examples of the structure that didn't work for you?

Here's one that I used to give you an idea:

Games:Test with spaces/688 Attack Sub/688AttackSub.slave
