### ISSUE TITLE
Changing Genres via initial GUI

### ISSUE THREAD

**Issue by IvanEBC** [MrZammler/iGame#46]
Hi There.

Present in BETA 2 and now BETA 3.

When adding a new non-WHDload game via the menu (I never scan)
I can type in the name i want
I can select the .slave it uses
but i can't change the genre, the button is stuck on Unknown

I click OK to add it anyways, find the one i just added, go to edit and properties, and in that window, i can change the Genre, so it isn't a big deal, but i guess in the initial slave adding window, it's there, but it doesn't work, be nice if it did :)

Hope you can reproduce and solve

Thank you.

**Comment by midwan** [comment]
@IvanEBC 
Thanks for reporting this, I'll take a look at it.

**Comment by MrZammler** [comment]
Hi Evan.

Can you check build: https://github.com/MrZammler/iGame/blob/master/iGame_rel/iGame-2018-10-25.lha ?

Should be fixed there.

**Comment by MrZammler** [comment]
Ah, sorry for the name.... :-(
