### ISSUE TITLE
Gameslist completely wiped

### ISSUE THREAD

**Issue by Troelz** [MrZammler/iGame#49]
Been running the latest version for some days now.
https://github.com/MrZammler/iGame/blob/master/iGame_rel/iGame-2018-11-01.lha

Suddenly the gameslist was completely wiped.
Fired up a game of Emerald Mine, played for a little while, then I quit.
The list of games where empty, and rebooting didn't help.

Looking at the gameslist it is now completely empty.

Also another feature to remove a non-whdload game would be sweet.
Right now it has the ad a non-whdload game, but if one is added, it cannot be removed again from the menu. One would have to find it on the gameslist and remove it.

Thanks again for all you effort, I hope you are making progress :)

**Comment by walkero-gr** [comment]
This might be a duplicate with #44 
Needs investigation

**Comment by walkero-gr** [comment]
This was not reported by anyone else all these years. So, it probably is fixed.
