### ISSUE TITLE
new igame 25/10/18 n 1/11/18 builds don't load on minimig aga core

### ISSUE THREAD

**Issue by uigiflip** [MrZammler/iGame#50]
maybe its minimigs non cycle accurate 68000 has same igame 25/10/18 build work on my 060 replay

**Comment by uigiflip** [comment]
i get software failure iGame Program failed (error #80000008) wait for disk activity to finish.

on both 25/10/18 n 1/11/18 builds

**Comment by uigiflip** [comment]
worked out needed to install mui, i think old version didn't need it

**Comment by midwan** [comment]
All versions of iGame required MUI, since the beginning. :)

**Comment by midwan** [comment]
@MrZammler I believe this can be closed then?

**Comment by uigiflip** [comment]
I think so, I forget what this was about.
