### ISSUE TITLE
Add option to launch non-WHDLoad games from Workbench or AmigaDOS

### ISSUE THREAD

**Issue by midwan** [MrZammler/iGame#51]
As some games refuse to be run from the command prompt (AmigaDOS), like Amijeweled, it would be nice to have the option to launch a game either from Workbench or AmigaDOS.

This only related to non-WHDLoad games, of course.

**Comment by midwan** [comment]
Workaround for now:
Use a script to launch the desired game through "WBStarter".

E.g.
`CD ""`
`C:WBStarter Amijeweled`
set the script to have the +s attribute!

**Comment by IvanEBC** [comment]
Yeah, as above, also, if you are on OS 3.5/3.9, i use WBRun which i think comes with the OS. 
WBRun <game> and it'll read the icon tooltypes and activate them as well.
I use it extensively in iGame.....

**Comment by MrZammler** [comment]
I've uploaded 2.0b5 which checks C for WBRun, and if found it will use that to run non-whdload games. I've sent a build to Jan from Amikit X to have a look too.

Thanks!

**Comment by IvanEBC** [comment]
Sounds good. But a lot of non WHDload stuff also doesn't NEED WBrun (usually only programs that use tooltypes i've found), so i wonder if it'll run unnecessarily or make a program not run properly at all if if used ALL the time?

**Comment by MrZammler** [comment]
Hi Ivan. I *think* it should be ok. I can't think of something that would suffer from this, if you know any, do please let me know. (wbrun might/should have a fallback for stuff that dont like starting from wb).
