### ISSUE TITLE
Swos  in-between black screens with 2.0b5 

### ISSUE THREAD

**Issue by aminta** [MrZammler/iGame#53]
Hi!

On 2.0b5 if I launch Swos 9596 or Swos 9697 with iGame and "CACHE" option when I select ie a team from Italy and then I exit to go to another country and select another team, I got an in-between black screen before and straight after the correct next screen.

The same when I go from my team to the "play match".

Hardware: Amiga 600 with Furia Card. Software: Classic Workbench Full.

No problem if I launch the same games from ie AGLaunch.

**Comment by walkero-gr** [comment]
Trying to figure out why this is happening, I need some more information from you, and maybe ypu need to do some tests.

1. Do you have the same issue with other games?
2. Do you have the same issue if you run the game from workbench? 
3. Do you have the same issue with previous versions of iGame and the specific game?
4. How many games do you have in iGame list?
5. How much available memory do you have before you run the game from iGame?
6. Did you test if there is a newer slave for the game that might resolve the issue?
