### ISSUE TITLE
68000 fix in Issue #24 and #33 are not working

### ISSUE THREAD

**Issue by Marina071170** [MrZammler/iGame#54]
I have found that the fix in Issue #24, or the fix in issue #33 did not lead to a build that would work on a 68000 CPU. Though the build is done smoothly.
The messages on the 68000 that I get are:
"Can't initialize application"
"Can't create application"
I'm testing this on FS-UAE emulator. Only when I switch to a 68EC020 or higher the build will work.

**Comment by walkero-gr** [comment]
@Marina071170 Is there a possibility that on 68000 MUI doesn't work well? I mean, are other MUI apps loading just fine?

**Comment by walkero-gr** [comment]
@Marina071170 I did an investigation for this issue. The problem is that iGame uses MCC_Texteditor which requires 68020+ and doesn't work on MC68000. 
@MrZammler We might need to remove that dependency so to support MC68000 CPU.

**Comment by Marina071170** [comment]
> @Marina071170 Is there a possibility that on 68000 MUI doesn't work well? I mean, are other MUI apps loading just fine?

I haven‘t looked into this ever since I bought an EC020 accelerator card

> @Marina071170 I did an investigation for this issue. The problem is that iGame uses MCC_Texteditor which requires 68020+ and doesn't work on MC68000.
> @MrZammler We might need to remove that dependency so to support MC68000 CPU.

Thanks for having a closer look. 👍

**Comment by walkero-gr** [comment]
@Marina071170 I found a 68000 version of MCC-TextEditor at Aminet, based on version 15.28. With this one iGame works just fine.
http://aminet.net/package/dev/mui/MCC_TextEditor_68k

@MrZammler We need to add this info in the documentation guide file.

**Comment by VincentGR76** [comment]
Indeed, there is a 68K version.
It runs fine on my A500+ with 3.1.
