### ISSUE TITLE
Open drawer from current game

### ISSUE THREAD

**Issue by T0lk13n** [MrZammler/iGame#55]
Would be nice to have the posibility to open the drawer containing the actual game.
Sometimes a slave needs to be updated and search and open the game drawer is tedious.
What do you think?

**Comment by T0lk13n** [comment]
Never mind mates. I have done it myself with my terrible C coding.

Thanks for this beauty.

**Comment by MrZammler** [comment]
Hi!

Sorry for not responing earlier... Would you like to create a pull request with this change?

Thanks!

**Comment by T0lk13n** [comment]
I could do it but dont know much about repositories and worse...I use OpenWorkbenchObject() which is a v44 (amigaos 3.5?) function and dont know if it sets the minimun requeriments of iGame.

**Comment by coldacid** [comment]
I've looked at your code, @T0lk13n, and I think I can clean it up, squish it down, and set up a PR for this.

**Comment by coldacid** [comment]
Regarding `OpenWorkbenchObjectA()` requiring workbench.library v44+ it should be possible to check the library version at startup and hide the functionality if the function is unavailable, right? That way minimum requirements don't have to be adjusted, but the functionality is there for people using a sufficiently advanced Amiga OS.

**Comment by T0lk13n** [comment]
Thanks @coldacid . It would be nice to have that feature.
And yes, checking the library version is a good idea to not break requirements.

**Comment by coldacid** [comment]
I've squashed the work with a few adjustments (mostly to maintain the ability to regenerate the catalog files with FlexCat) in https://github.com/coldacid/iGame/tree/OpenCurrentDir -- so far this is all your work @T0lk13n, just with a few changes unrelated to the functionality rearranged or removed. At this point I'll add in the workbench.library check and hide the functionality when `OpenWorkbenchObjectA()` is unavailable.

**Comment by coldacid** [comment]
@walkero-gr what version of workbench.library comes with 3.1.4? If it's less than v44, could you test this branch and see what happens?

**Comment by T0lk13n** [comment]
Looking at https://www.gregdonner.org/workbench/wb_314.html 3.1.4 is v45.

**Comment by coldacid** [comment]
@T0lk13n I've seen that myself, but that version number doesn't necessarily mean the version of workbench.library. It could be, it could be the version of Exec, it could be the version of AmigaDOS... Without that page explicitly stating that it's the workbench.library version I can't be sure and I can't feel comfortable with it as a source.

**Comment by T0lk13n** [comment]
I have installed 3.1.4 right now in my a1260.
Workbench.library > 45.194

**Comment by walkero-gr** [comment]
@coldacid  Workbench is 45.149

**Comment by coldacid** [comment]
Okay, so definitely too up to date to test that the app doesn't crash from trying to skip the menu item.

**Comment by T0lk13n** [comment]
The only 3.1 setup I could try is under winuae.

**Comment by coldacid** [comment]
@T0lk13n if you have an emulated 3.1 setup with MUI installed, that should be fine. It's just that I don't.

**Comment by T0lk13n** [comment]
Perhaps I should install a few dependencies but it's not a problem. I could try it.

**Comment by coldacid** [comment]
Thanks, if you would.

**Comment by T0lk13n** [comment]
I was a bit busy but I have compiled and tried igame in a clean wb3.1 install.
I can see the menu but obviously nothing happends if I try to use it so seems it works as it should.

**Comment by coldacid** [comment]
Huh. The code I wrote for the PR should hide the menu item on a non-upgraded 3.1 but show it on 3.5 and later.

**Comment by T0lk13n** [comment]
I have used your code. I see functions like get_wb_version() and the check in iGameGUI.c so dont know why is showed in OS 3.1.

**Comment by coldacid** [comment]
I checked to see if I had logic flipped around, but it looks correct. What machine ROM are you using (A1200, A4000, A4000T), and what does `version workbench.library` in the shell report?

**Comment by T0lk13n** [comment]
Im using a 1200 ROM (40.68) and workbench.library version 40.5.

**Comment by coldacid** [comment]
Yeah, that's really odd then. It shouldn't show the open drawer menu item in that situation. I wonder what's going on!

**Comment by coldacid** [comment]
Oh, I think I might know what the issue is. I bet `lib_Version` is packed version and revision together, and I need to unpack that. It being treated as just a `ULONG` in the headers mislead me.

**Comment by T0lk13n** [comment]
True. looking at Library struct there is an UWORLD for the version and another one for the revision.

**Comment by coldacid** [comment]
Okay with separate value for revision means it probably isn't packed. I'll have to reexamine this.

**Comment by T0lk13n** [comment]
I ha toying a bit this weekend and I think the problem is we are using -auto and then Workbench library is already opened and OpenLibrary always shows 0;

We need only its WorkbenchBase.
including <proto/wb.h>

and get_wb_version() something simpler
ULONG get_wb_version()
{
	static ULONG ver = 0;
	
	if (ver != 0UL)
	{
		return ver;
	}

	if (WorkbenchBase == NULL)
	{
		//Really Workbench library shold be already opened
		// Somehow we're running without Workbench.
		// Nothing to do since the version variable inits with 0.
		return ver;
	}
	// Save workbench.library version for later calls
	ver = WorkbenchBase->lib_Version;

	return ver;
}

This way ver = 51 in my MorphOS setup. Before was always 0.

Checked in wb 3.1 and now It doesnt show the menu.

**Comment by coldacid** [comment]
Thanks for figuring it out! I'll update the code from this.
