### ISSUE TITLE
Show proper app icon when iconifying

### ISSUE THREAD

**Issue by coldacid** [MrZammler/iGame#76]
Currently iconifying iGame via the MUI menu shows the default MUI icon instead of the iGame icon. We should figure out how to show the icon for the app itself when it is iconified.

**Comment by walkero-gr** [comment]
With this PR (https://github.com/MrZammler/iGame/pull/78) this should be fixed.

**Comment by coldacid** [comment]
I'm trying it out on my personal integration branch and it works great!

**Comment by coldacid** [comment]
Closed by #78.
