### ISSUE TITLE
warning 91 in line 2960 of "src/funcs.c": assignment discards const

### ISSUE THREAD

**Issue by walkero-gr** [MrZammler/iGame#89]
I get the warning **warning 91 in line 2960 of "src/funcs.c": assignment discards const** when compiling 68K and MOS versions

https://github.com/MrZammler/iGame/blob/master/src/funcs.c#L2960

You can see it at https://drone-gh.intercube.gr/walkero-gr/iGame/64/1/2 as well

@coldacid Any thoughts?

**Comment by coldacid** [comment]
@walkero-gr yep, I see what's wrong. The declaration for `path_only` on line 2929 should not be `const`.

**Comment by walkero-gr** [comment]
Nice... Would you like to create a PR for that?

**Comment by coldacid** [comment]
No problem, just gotta get my repo and my branches all up to date first.

**Comment by coldacid** [comment]
@walkero-gr @MrZammler PR #90 is ready to take care of this.
