### ISSUE TITLE
cvs generation issue

### ISSUE THREAD

**Issue by MrV2K** [MrZammler/iGame#94]
Genres are added to slot 3 in the csv entry but are in slot 5 when no entry is added. e.g.

0;1000 Miglia;Driving / Car (Chase View);Games:WHDGames/0-9/1000Miglia/1000miglia.slave;1;3;1;0
0;1000cc Turbo;Games:WHDGames/0-9/1000ccTurbo/1000ccturbo.slave;0;0;0;0;0

**Comment by walkero-gr** [comment]
@MrV2K Thank you for this report. I am going to have a look on this. Can you please attach here the gameslist and gameslist.csv files? The will help me reproduce the problem.

**Comment by MrV2K** [comment]
Attached for you...
[iGame.zip](https://github.com/MrZammler/iGame/files/5196846/iGame.zip)
I'm also writing a little windows utility that fixes the gameslist names and adds genres...
![igame](https://user-images.githubusercontent.com/71010565/92630284-8743c280-f2c7-11ea-9848-ff8260ed51ef.png)

**Comment by walkero-gr** [comment]
@MrV2K The CSV file I see in your zip is not like the pasted text above... What I see in your file is a good working CSV file

```
0;1000 Miglia;Driving / Car (Chase View);Games:WHDGames/0-9/1000Miglia/1000miglia.slave;1;1;1;0
0;1000cc Turbo;Driving / Bike (Chase View);Games:WHDGames/0-9/1000ccTurbo/1000ccturbo.slave;0;0;0;0
```

**Comment by walkero-gr** [comment]
@MrV2K Those that do not have any genre set, do not save anything in CSV, which is the right way to do it, i.e. 

```
0;Anarchy;;Games:WHDGames/A/Anarchy/anarchy.slave;0;0;0;0
0;Amnios;;Games:WHDGames/A/Amnios/amnios.slave;0;0;0;0
```

**Comment by MrV2K** [comment]
This is what I have in the gameslist.csv that was just generated from the last release (iGame-2020-09-04.lha)...

0;Anarchy;Games:WHDGames/A/Anarchy/anarchy.slave;0;0;0;0;0
0;Amnios;Games:WHDGames/A/Amnios/amnios.slave;0;0;0;0;0

Maybe the source is more up to date.

I'm hand doing the genres at the moment. I've already done the game names based on the folder and slave names (no more alt alt alt!). I've also extracted language, AGA , CD32, CDTV, NTSC & MT32 data from the folder names which is stored in the database too. It's all saved in a compressed json file which the program uses to fix the names as it loads the gamelist.

**Comment by walkero-gr** [comment]
@MrV2K Can you please try the attached version? Just remember to delete the generated CSV file from the iGame folder and replaced the executable with the one from the attached file. There are multiple CPU versions, choose the one that suits your system. Please tell me if that fixes the problem. Thanks.

[iGame_issue94_hotfix.zip](https://github.com/MrZammler/iGame/files/5197281/iGame_issue94_hotfix.zip)

**Comment by MrV2K** [comment]
This fixes the problem! Thanks.
