### ISSUE TITLE
Slave and icon filename checks are case-sensitive

### ISSUE THREAD

**Issue by coldacid** [MrZammler/iGame#97]
(Split from https://github.com/MrZammler/iGame/issues/74#issuecomment-680142638)

>One other item of note exists for this use-case, however: We need to lowercase the ".slave" part of the filename so that the icon will be properly identified for launch purposes and so that we display the appropriate image in the sidebar if there's no iGame.iff in the drawer of the game.

Because the filename checks for slaves and icons are case-sensitive (due to `strstr()`), slave with upper or mixed case file name extensions will not be properly recognized and treated as a WHDLoad slave except in the single instance of executing the slave via WHDLoad. These filename checks should be case-insensitive so that we will always act appropriately with WHDLoad slaves regardless of the capitalization in their filename extensions.

**Comment by coldacid** [comment]
@walkero-gr: I'd say this is a bug, not an enhancement. It's something I've encountered already from adding slaves via the menu, which is how I discovered it in the first place.

**Comment by walkero-gr** [comment]
@coldacid Since this is a bug, I set it for v2.0 milestone. Only bugs will enter on this version for now, so that we can have a stable 2.0 version as soon as possible.
@MrZammler @coldacid Do you guys agree?

**Comment by coldacid** [comment]
Yes, with the one caveat of renaming the menu item for adding games individually per #74 since that's already in the milestone for v2.0.

The work I'm looking at for non-WHDLoad icons and iconify-on-game-start will be 2.1 or beyond.
